[pytest]

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

addopts = -v

markers =
    api: API Test
    ui: UI Test
    smoke: Smoke Test
    regression: Regression Test
    sanity: Sanity Test
    negative: Negative Test

; cách chạy pytest -m api và tương tự
; hoặc pytest -m "api and regression"